#!/bin/bash
#
# https://
#
P=lua
V=${LUA_VERSION:-5.4.6}
FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="http://www.lua.org/ftp/$P-$V.tar.gz"

source "$(dirname "$0")/librecipes.bash"

#---
# configure

LUA_PREFIX="${PREFIX}/libexec/lua"
export INSTALL_TOP="${LUA_PREFIX}"
PATH="${LUA_PREFIX}/bin:$PATH" 
sed -i "s;/usr/local/;${INSTALL_TOP}/;" "${SRC_DIR}/src/luaconf.h"
#---
# compile & install
make -e -j ${NJOBS} || exit ${PB_ERR_MAKE}
make -e install || exit ${PB_ERR_INSTALL}

#---
# post-install

#---
# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
