#!/bin/bash
#
# https://
#
#---
LUA_PREFIX="${PREFIX}/libexec/lua"
PATH="${LUA_PREFIX}/bin:$PATH" 

"${LUA_PREFIX}/bin/luarocks" install --tree "${LUA_PREFIX}" luaposix

#---
# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
