#!/bin/bash
#
# https://
#
#---
LUA_PREFIX="${PREFIX}/libexec/lua"
PATH="${LUA_PREFIX}/bin:$PATH" 

luarocks install --tree "${LUA_PREFIX}/share/lua/5.4" luaposix

#---
# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
