#!/bin/zsh

#############################################################################
# initialize zsh completion
#
# :FIXME:

#############################################################################
# legacy...
#
unset MODULE_VERSION
unset MODULE_VERSION_STACK
unset MODULESHOME

#############################################################################
# implement module comand as shell function
#
declare -- PMODULES_HOME=$0:A:h:h

declare -- _cmd_="module() {
        unset BASH_ENV
        local output=\"\$(\"${PMODULES_HOME}/bin/modulecmd\" zsh \"\$@\")\"
        eval \"\${output}\"
}"

eval "$(echo "${_cmd_}")"
export -f module

_cmd_="modbuild(){
	\"${PMODULES_HOME}/bin/modbuild\" \"\$@\"
}"
eval "$(echo "${_cmd_}")"
export -f modbuild

unset _cmd_

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
